# UCM Configuration File Example
# 
# This file demonstrates how to configure UCM using YAML.
# You can use this config file by setting the path to this file in kv_connector_extra_config in launch script or command line like this:
# kv_connector_extra_config={"UCM_CONFIG_FILE": "/workspace/unified-cache-management/examples/ucm_config_example.yaml"}
#
# Alternatively, you can still use kv_connector_extra_config in KVTransferConfig
# for backward compatibility.

ucm_connectors:
  - ucm_connector_name: "UcmPipelineStore"
    ucm_connector_config:
      store_pipeline: "Cache|Posix"
      storage_backends: "/mnt/test"
      posix_capacity_gb: 10240
      posix_io_engine: "psync"
      posix_data_trans_concurrency: 128
